<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7OO510B" failures="1" tests="3" name="com.fashion.testcases.ForgotPasswordcicd" time="4.652" errors="0" timestamp="2025-09-19T13:17:11 IST" skipped="0">
  <testcase classname="com.fashion.testcases.ForgotPasswordcicd" name="forgotPass" time="3.183"/>
  <testcase classname="com.fashion.testcases.ForgotPasswordcicd" name="validation" time="0.756"/>
  <testcase classname="com.fashion.testcases.ForgotPasswordcicd" name="enteredWrongEmail" time="0.713">
    <failure message="Wrong error message shown! expected [A reset link is sent to this mail ID.] but found [We couldn&#039;t find an account with that email. Please try again or sign up.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Wrong error message shown! expected [A reset link is sent to this mail ID.] but found [We couldn't find an account with that email. Please try again or sign up.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.fashion.testcases.ForgotPasswordcicd.enteredWrongEmail(ForgotPasswordcicd.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.fashion.testcases.Runner.main(Runner.java:19)
]]>
    </failure>
  </testcase> <!-- enteredWrongEmail -->
</testsuite> <!-- com.fashion.testcases.ForgotPasswordcicd -->
